# Download and set up Eigen

include(cmake/Externals.cmake)

ExternalProject_Add(romocc
        PREFIX ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc
        BINARY_DIR ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc
        GIT_REPOSITORY "https://github.com/SINTEFMedtek/libromocc.git"
        GIT_TAG "bbd2043ab0b99b571d1dcb0d2dc7ffc6ad6dd623"
        CMAKE_ARGS
            -DROMOCC_BUILD_TESTS:BOOL=OFF
            -DROMOCC_BUILD_EXAMPLES:BOOL=OFF
            -DROMOCC_BUILD_URSIMULATOR:BOOL=OFF
        CMAKE_CACHE_ARGS
            -DCMAKE_BUILD_TYPE:STRING=Release
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF
            -DCMAKE_INSTALL_MESSAGE:BOOL=LAZY
            -DCMAKE_INSTALL_PREFIX:PATH=${ECHOBOT_EXTERNAL_INSTALL_DIR}
        )

if(WIN32)
    set(ROMOCC_LIBRARY romocc.lib)
else()
    set(ROMOCC_LIBRARY ${CMAKE_SHARED_LIBRARY_PREFIX}romocc${CMAKE_SHARED_LIBRARY_SUFFIX})
    set(ROMOCC_INCLUDE_DIRS ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc/include ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc/src/romocc/source)
    set(ROMOCC_LIBRARY_DIR ${ECHOBOT_EXTERNAL_BUILD_DIR}/romocc/lib)
    link_directories(${ROMOCC_LIBRARY_DIR})
endif()

list(APPEND ECHOBOT_INCLUDE_DIRS ${ROMOCC_INCLUDE_DIRS})
list(APPEND LIBRARIES ${ROMOCC_LIBRARY})
list(APPEND ECHOBOT_EXTERNAL_DEPENDENCIES romocc)