include(ExternalProject)

set(FASTROMO_DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/external/)
set(FASTROMO_EXTERNAL_BUILD_DIR ${PROJECT_BINARY_DIR}/external)
set(FASTROMO_EXTERNAL_INSTALL_DIR ${PROJECT_BINARY_DIR})
