include(ExternalProject)

set(ECHOBOT_DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/external/)
set(ECHOBOT_EXTERNAL_BUILD_DIR ${PROJECT_BINARY_DIR}/external)
set(ECHOBOT_EXTERNAL_INSTALL_DIR ${PROJECT_BINARY_DIR})
